/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTradingRouteImport } from './routes/_authenticated/trading'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMarketsRouteImport } from './routes/_authenticated/markets'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicSnapshotPortfolioRouteImport } from './routes/api/public/snapshot-portfolio'
import { Route as ApiPublicResolveSignalsRouteImport } from './routes/api/public/resolve-signals'
import { Route as ApiPublicGenerateStrategiesRouteImport } from './routes/api/public/generate-strategies'
import { Route as ApiPublicEvaluateStrategiesRouteImport } from './routes/api/public/evaluate-strategies'
import { Route as ApiPublicEvaluateAlertsRouteImport } from './routes/api/public/evaluate-alerts'
import { Route as ApiPublicDailyDigestRouteImport } from './routes/api/public/daily-digest'
import { Route as ApiPublicAutonomousExitCheckRouteImport } from './routes/api/public/autonomous-exit-check'
import { Route as ApiPublicAutonomousAgentRouteImport } from './routes/api/public/autonomous-agent'
import { Route as ApiPublicMcpRobinhoodCallbackRouteImport } from './routes/api/public/mcp/robinhood/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTradingRoute = AuthenticatedTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketsRoute = AuthenticatedMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSnapshotPortfolioRoute =
  ApiPublicSnapshotPortfolioRouteImport.update({
    id: '/api/public/snapshot-portfolio',
    path: '/api/public/snapshot-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResolveSignalsRoute = ApiPublicResolveSignalsRouteImport.update({
  id: '/api/public/resolve-signals',
  path: '/api/public/resolve-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateStrategiesRoute =
  ApiPublicGenerateStrategiesRouteImport.update({
    id: '/api/public/generate-strategies',
    path: '/api/public/generate-strategies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvaluateStrategiesRoute =
  ApiPublicEvaluateStrategiesRouteImport.update({
    id: '/api/public/evaluate-strategies',
    path: '/api/public/evaluate-strategies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvaluateAlertsRoute = ApiPublicEvaluateAlertsRouteImport.update({
  id: '/api/public/evaluate-alerts',
  path: '/api/public/evaluate-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyDigestRoute = ApiPublicDailyDigestRouteImport.update({
  id: '/api/public/daily-digest',
  path: '/api/public/daily-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutonomousExitCheckRoute =
  ApiPublicAutonomousExitCheckRouteImport.update({
    id: '/api/public/autonomous-exit-check',
    path: '/api/public/autonomous-exit-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutonomousAgentRoute =
  ApiPublicAutonomousAgentRouteImport.update({
    id: '/api/public/autonomous-agent',
    path: '/api/public/autonomous-agent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMcpRobinhoodCallbackRoute =
  ApiPublicMcpRobinhoodCallbackRouteImport.update({
    id: '/api/public/mcp/robinhood/callback',
    path: '/api/public/mcp/robinhood/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trading': typeof AuthenticatedTradingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/autonomous-agent': typeof ApiPublicAutonomousAgentRoute
  '/api/public/autonomous-exit-check': typeof ApiPublicAutonomousExitCheckRoute
  '/api/public/daily-digest': typeof ApiPublicDailyDigestRoute
  '/api/public/evaluate-alerts': typeof ApiPublicEvaluateAlertsRoute
  '/api/public/evaluate-strategies': typeof ApiPublicEvaluateStrategiesRoute
  '/api/public/generate-strategies': typeof ApiPublicGenerateStrategiesRoute
  '/api/public/resolve-signals': typeof ApiPublicResolveSignalsRoute
  '/api/public/snapshot-portfolio': typeof ApiPublicSnapshotPortfolioRoute
  '/api/public/mcp/robinhood/callback': typeof ApiPublicMcpRobinhoodCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trading': typeof AuthenticatedTradingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/autonomous-agent': typeof ApiPublicAutonomousAgentRoute
  '/api/public/autonomous-exit-check': typeof ApiPublicAutonomousExitCheckRoute
  '/api/public/daily-digest': typeof ApiPublicDailyDigestRoute
  '/api/public/evaluate-alerts': typeof ApiPublicEvaluateAlertsRoute
  '/api/public/evaluate-strategies': typeof ApiPublicEvaluateStrategiesRoute
  '/api/public/generate-strategies': typeof ApiPublicGenerateStrategiesRoute
  '/api/public/resolve-signals': typeof ApiPublicResolveSignalsRoute
  '/api/public/snapshot-portfolio': typeof ApiPublicSnapshotPortfolioRoute
  '/api/public/mcp/robinhood/callback': typeof ApiPublicMcpRobinhoodCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/markets': typeof AuthenticatedMarketsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trading': typeof AuthenticatedTradingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/autonomous-agent': typeof ApiPublicAutonomousAgentRoute
  '/api/public/autonomous-exit-check': typeof ApiPublicAutonomousExitCheckRoute
  '/api/public/daily-digest': typeof ApiPublicDailyDigestRoute
  '/api/public/evaluate-alerts': typeof ApiPublicEvaluateAlertsRoute
  '/api/public/evaluate-strategies': typeof ApiPublicEvaluateStrategiesRoute
  '/api/public/generate-strategies': typeof ApiPublicGenerateStrategiesRoute
  '/api/public/resolve-signals': typeof ApiPublicResolveSignalsRoute
  '/api/public/snapshot-portfolio': typeof ApiPublicSnapshotPortfolioRoute
  '/api/public/mcp/robinhood/callback': typeof ApiPublicMcpRobinhoodCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/markets'
    | '/settings'
    | '/trading'
    | '/api/chat'
    | '/api/public/autonomous-agent'
    | '/api/public/autonomous-exit-check'
    | '/api/public/daily-digest'
    | '/api/public/evaluate-alerts'
    | '/api/public/evaluate-strategies'
    | '/api/public/generate-strategies'
    | '/api/public/resolve-signals'
    | '/api/public/snapshot-portfolio'
    | '/api/public/mcp/robinhood/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/markets'
    | '/settings'
    | '/trading'
    | '/api/chat'
    | '/api/public/autonomous-agent'
    | '/api/public/autonomous-exit-check'
    | '/api/public/daily-digest'
    | '/api/public/evaluate-alerts'
    | '/api/public/evaluate-strategies'
    | '/api/public/generate-strategies'
    | '/api/public/resolve-signals'
    | '/api/public/snapshot-portfolio'
    | '/api/public/mcp/robinhood/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/markets'
    | '/_authenticated/settings'
    | '/_authenticated/trading'
    | '/api/chat'
    | '/api/public/autonomous-agent'
    | '/api/public/autonomous-exit-check'
    | '/api/public/daily-digest'
    | '/api/public/evaluate-alerts'
    | '/api/public/evaluate-strategies'
    | '/api/public/generate-strategies'
    | '/api/public/resolve-signals'
    | '/api/public/snapshot-portfolio'
    | '/api/public/mcp/robinhood/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicAutonomousAgentRoute: typeof ApiPublicAutonomousAgentRoute
  ApiPublicAutonomousExitCheckRoute: typeof ApiPublicAutonomousExitCheckRoute
  ApiPublicDailyDigestRoute: typeof ApiPublicDailyDigestRoute
  ApiPublicEvaluateAlertsRoute: typeof ApiPublicEvaluateAlertsRoute
  ApiPublicEvaluateStrategiesRoute: typeof ApiPublicEvaluateStrategiesRoute
  ApiPublicGenerateStrategiesRoute: typeof ApiPublicGenerateStrategiesRoute
  ApiPublicResolveSignalsRoute: typeof ApiPublicResolveSignalsRoute
  ApiPublicSnapshotPortfolioRoute: typeof ApiPublicSnapshotPortfolioRoute
  ApiPublicMcpRobinhoodCallbackRoute: typeof ApiPublicMcpRobinhoodCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trading': {
      id: '/_authenticated/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof AuthenticatedTradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/markets': {
      id: '/_authenticated/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AuthenticatedMarketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/snapshot-portfolio': {
      id: '/api/public/snapshot-portfolio'
      path: '/api/public/snapshot-portfolio'
      fullPath: '/api/public/snapshot-portfolio'
      preLoaderRoute: typeof ApiPublicSnapshotPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resolve-signals': {
      id: '/api/public/resolve-signals'
      path: '/api/public/resolve-signals'
      fullPath: '/api/public/resolve-signals'
      preLoaderRoute: typeof ApiPublicResolveSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-strategies': {
      id: '/api/public/generate-strategies'
      path: '/api/public/generate-strategies'
      fullPath: '/api/public/generate-strategies'
      preLoaderRoute: typeof ApiPublicGenerateStrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evaluate-strategies': {
      id: '/api/public/evaluate-strategies'
      path: '/api/public/evaluate-strategies'
      fullPath: '/api/public/evaluate-strategies'
      preLoaderRoute: typeof ApiPublicEvaluateStrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evaluate-alerts': {
      id: '/api/public/evaluate-alerts'
      path: '/api/public/evaluate-alerts'
      fullPath: '/api/public/evaluate-alerts'
      preLoaderRoute: typeof ApiPublicEvaluateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-digest': {
      id: '/api/public/daily-digest'
      path: '/api/public/daily-digest'
      fullPath: '/api/public/daily-digest'
      preLoaderRoute: typeof ApiPublicDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autonomous-exit-check': {
      id: '/api/public/autonomous-exit-check'
      path: '/api/public/autonomous-exit-check'
      fullPath: '/api/public/autonomous-exit-check'
      preLoaderRoute: typeof ApiPublicAutonomousExitCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autonomous-agent': {
      id: '/api/public/autonomous-agent'
      path: '/api/public/autonomous-agent'
      fullPath: '/api/public/autonomous-agent'
      preLoaderRoute: typeof ApiPublicAutonomousAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp/robinhood/callback': {
      id: '/api/public/mcp/robinhood/callback'
      path: '/api/public/mcp/robinhood/callback'
      fullPath: '/api/public/mcp/robinhood/callback'
      preLoaderRoute: typeof ApiPublicMcpRobinhoodCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMarketsRoute: typeof AuthenticatedMarketsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTradingRoute: typeof AuthenticatedTradingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMarketsRoute: AuthenticatedMarketsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTradingRoute: AuthenticatedTradingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicAutonomousAgentRoute: ApiPublicAutonomousAgentRoute,
  ApiPublicAutonomousExitCheckRoute: ApiPublicAutonomousExitCheckRoute,
  ApiPublicDailyDigestRoute: ApiPublicDailyDigestRoute,
  ApiPublicEvaluateAlertsRoute: ApiPublicEvaluateAlertsRoute,
  ApiPublicEvaluateStrategiesRoute: ApiPublicEvaluateStrategiesRoute,
  ApiPublicGenerateStrategiesRoute: ApiPublicGenerateStrategiesRoute,
  ApiPublicResolveSignalsRoute: ApiPublicResolveSignalsRoute,
  ApiPublicSnapshotPortfolioRoute: ApiPublicSnapshotPortfolioRoute,
  ApiPublicMcpRobinhoodCallbackRoute: ApiPublicMcpRobinhoodCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
